config/routes.rb
Rails.application.routes.draw do

  root 'start_session#index'
  
  get '/signin' => 'start_session#signin'
  get '/signup' => 'start_session#signup'
  post '/do_signup' => 'start_session#do_signup'
  post '/do_signin' => 'start_session#do_signin'
  get '/logout' => 'session#logout'

  get '/profile' => 'session#profile'
  get '/settings' => 'session#settings'

  namespace :admin do
    resources :users
    resources :grocery_lists
    resources :store_products
    resources :products
    resources :stores
  end

end

app/models/store_product.rb
class StoreProduct < ActiveRecord::Base
	# If the user enters a product it goes into the database and is able to be reviewed by other users.
	# If it is downvoted by 3 different users (does this product and grocery store exist? y/n) then the admin is sent an
	# email to review this product and store. If the product and store was deemed correct the product stays but the
	# ability for users to say y/n this product exists is gone.
	# If 5 users say this product and store exists, an email will be sent to an admin to review this product as
	# permenant and the admin can remove the ability to vote.

	# Is this price correct? Is the tax correct?

	# should the user get a message their product was incorrect? Or voted incorrect and is in review? And possibly
	# be able to prove this store exists?
	# possibly limit number of entries per day and/or per minute

	# The goal is to do your best to not allow the user to have free rein over your database like myfitnesspal aka a
	# cake with 0 carbs... or the like for Grocery Cost App $10,000 cheese cake from Walmart.
	# Let the user do the research for you, and regulate the research for you to extents.

	belongs_to :grocery_list
	belongs_to :store
	belongs_to :product
end

app/controllers/admin/store_products_controller.rb
class Admin::StoreProductsController < Admin::BaseController
	def index
  	@store_products = StoreProduct.all
  end

  def new
  	@store_product = StoreProduct.new
  end

  def create
  	@store_product = StoreProduct.new(store_product_params)
  	if @store_product.save
  		redirect_to admin_store_products_path, :notice => "Store product created."
  	else
  		render :new, :notice => "Could not be created."
  	end
  end

  def edit
  	@store_product = StoreProduct.find(params[:id])
  end

  def update
  	@store_product = StoreProduct.find(params[:id])
    if @store_product.save
      redirect_to edit_admin_store_products_path, :notice => "Updated store product."
    else
      render :edit, :notice => "Could not be updated."
    end
  end

  def destroy
  	StoreProduct.find(params[:id]).destroy
  	redirect_to admin_store_products_path, :notice => "Store product deleted."
  end
end

app/controllers/store_product_controller.rb
class StoreProductController < AuthenticatedController
	def grocery_list
		# @grocery_list = GroceryList.new
	end

	def do_grocery_list
		# @grocery_list = GroceryList.create(grocery_list_params)
		# redirect_to profile_path
	end

	def grocery_list_params
		# params.require(:grocery_list).permit(if this is a then :title, :body)
	end
end

app/controllers/store_products_controller.rb
class StoreProductsController < AuthenticatedController
	def grocery_list
		# @grocery_list = GroceryList.new
	end

	def do_grocery_list
		# @grocery_list = GroceryList.create(grocery_list_params)
		# redirect_to profile_path
	end

	def grocery_list_params
		# params.require(:grocery_list).permit(if this is a then :title, :body)
	end
end

app/views/admin/store_products/edit.html.erb
<h1>Edit Store Product</h1>
<div class="container-fluid">
	<div class="row">
		<div class="col-md-3"></div>
		<div class="col-md-6">
			<h2>Products</h2>
				<%= form_for @store_products, url: admin_store_product_path(@store_product.id), :html => { method: :patch } do |f| %>
					<%= label_tag(:store_product_name, "Store product name") %>
				  <%= @store_product.name %>
				<!-- <div class="form-group">
				  user can vote on product user, cannot vote on product
				</div> -->
				<div class="form-group">
					<%= f.submit "Edit", class: "btn btn-primary" %>
				</div>
				<% end %>
			</div>
		<div class="col-md-3"></div>
	</div>
</div>

app/views/admin/store_products/index.html.erb
<h1>Store Products</h1>
<h3><%= link_to "+ Add new", new_admin_store_product_path %></h3>
<table class="table table-striped">
	<tr>
		<th>Store Product Id</th>
		<th>Store Product Name</th>
		<th>Edit</th>
		<th>Delete</th>
	</tr>
	<% @store_products.each do |store_product| %>
	  <tr>
	    <td><%= store_product.id %></td>
	    <td><%= store_product.name %></td>
	    <td><%= link_to "Edit", edit_admin_store_product_path(:id => store_product.id) %></td>
	    <td><%= link_to "Delete", admin_store_product_path(:id => store_product.id), data: { :confirm => "Are you sure?" }, method: :delete %></td>
	  </tr>
	<% end %>
</table>

app/views/admin/store_products/new.html.erb
<div class="container-fluid">
	<div class="row">
		<div class="col-md-3"></div>
		<div class="col-md-6">
			<h2>New Store Product</h2>
				<%= form_for @store_product, url: new_admin_store_product_path do |f| %>
				  <%= render "shared/validation_messages", :target => @store_product %>
				<div class="form-group">
					<%= f.label :store_name, class: "control-label" %>
					<%= f.text_field :name, :placeholder => "Enter a store name", class: "form-control" %>
				  <!-- store address -->
				  <%= f.label :product_name, class: "control-label" %>
					<%= f.text_field :name, :placeholder => "Enter a product name", class: "form-control" %>
					<!-- optional brand -->
					<!-- cost -->
				</div>
				<div class="form-group">
				  <%= f.submit "Create", class: "btn btn-primary" %>
				</div>
				<% end %>
			</div>
		<div class="col-md-3"></div>
	</div>
</div>