config/routes.rb
Rails.application.routes.draw do

  root 'start_session#index'
  
  get '/signin' => 'start_session#signin'
  get '/signup' => 'start_session#signup'
  post '/do_signup' => 'start_session#do_signup'
  post '/do_signin' => 'start_session#do_signin'
  get '/logout' => 'session#logout'

  get '/profile' => 'session#profile'
  get '/settings' => 'session#settings'

  namespace :admin do
    resources :users
    resources :grocery_lists
    resources :store_products
    resources :products
    resources :stores
  end

end

app/models/grocery_list.rb
class GroceryList < ActiveRecord::Base
	belongs_to :user
	has_many :store_products
	accepts_nested_atrributes_for :store_products
end

app/controllers/admin/grocery_lists_controller.rb
class Admin::GroceryListsController < Admin::BaseController
	def index
  	@grocery_lists = GroceryList.all
  end
  
  def new
    @grocery_list = GroceryList.new
  end

  def create
    @grocery_list = GroceryList.new(grocery_list_params)
    if @grocery_lists.save
      redirect_to new_admin_grocery_lists_path, :notice => "New product created."
    else
      render :new, :notice => "Could not be created."
    end
  end

  def edit
    @grocery_list = GroceryList.find(params[:id])
  end

  def update
    @grocery_list = GroceryList.find(params[:id])
    if @grocery_lists.update_attributes(grocery_list_params)
      redirect_to edit_admin_grocery_lists_path, :notice => "Grocery list updated."
    else
      render :edit, :notice => "Could not be updated."
    end
  end

  def destroy
    GroceryList.find(params[:id]).destroy
    redirect_to admin_grocery_lists_path, :notice => "Grocery list deleted."
  end
end

app/views/admin/grocery_lists/edit.html.erb
<h1>Edit Grocery List</h1>
<div class="container-fluid">
	<div class="row">
		<div class="col-md-3"></div>
		<div class="col-md-6">
			<h2>Products</h2>
			<%= form_for [:admin, @grocery_lists], :html => { method: :patch } do |f| %>
				<%= f.label(:grocery_list_name, "Grocery list name") %>
			  <%= f.text_area :name, :placeholder => "Edit grocery list.", class: "form-control" %>
			<div class="form-group">
				<%= f.submit "Edit", class: "btn btn-primary" %>
			</div>
			<% end %>
			</div>
		<div class="col-md-3"></div>
	</div>
</div>

app/views/admin/grocery_lists/index.html.erb
<h1>Grocery Lists</h1>
<h3><%= link_to "+ Add new", new_admin_grocery_list_path %></h3>
<table class="table table-striped">
	<tr>
		<th>Grocery List Id</th>
		<th>Grocery List Name</th>
		<th>Edit</th>
		<th>Delete</th>
	</tr>
	<% @grocery_lists.each do |grocery_list| %>
	  <tr>
	    <td><%= grocery_list.id %></td>
	    <td><%= grocery_list.name %></td>
	    <td><%= link_to "Edit", edit_admin_grocery_list_path(:id => grocery_list.id) %></td>
	    <td><%= link_to "Delete", admin_grocery_list_path(:id => grocery_list.id), data: { :confirm => "Are you sure?" }, method: :delete %></td>
	  </tr>
	<% end %>
</table>

app/views/admin/grocery_lists/new.html.erb
<div class="container-fluid">
	<div class="row">
		<div class="col-md-3"></div>
		<div class="col-md-6">
			<h2>New Store</h2>
			<%= form_for [:admin, @grocery_list] do |f| %>
			<div class="form-group">
				<%= f.label :grocery_list, class: "control-label" %>
				<%= f.text_area :body, :placeholder => "Enter a grocery list", class: "form-control" %>
			</div>
			<div class="form-group">
			  <%= f.submit "Create", class: "btn btn-primary" %>
			</div>
			<% end %>
		</div>
		<div class="col-md-3"></div>
	</div>
</div>