config/routes.rb
Rails.application.routes.draw do

  root 'start_session#index'
  
  get '/signin' => 'start_session#signin'
  get '/signup' => 'start_session#signup'
  post '/do_signup' => 'start_session#do_signup'
  post '/do_signin' => 'start_session#do_signin'
  get '/logout' => 'session#logout'

  get '/profile' => 'session#profile'
  get '/settings' => 'session#settings'

  namespace :admin do
    resources :users
    resources :grocery_lists
    resources :store_products
    resources :products
    resources :stores
  end

end

app/controllers/start_session_controller.rb
class StartSessionController < UnauthenticatedController
  def index
  end

	def signin
		@user = User.new
	end

  def do_signin
  	@user = User.find_by(email: params[:user][:email])
  	if @user.authenticate(params[:user][:password])
  		session[:user_id] = @user.id
			redirect_to profile_path
	  else
		  render :signin
		end
  end

	def signup
		@user = User.new
	end

	def do_signup
		@user = User.new(user_params)
		if @user.save
  		session[:user_id] = @user.id
			redirect_to profile_path
		else
			render :signup
		end
	end
end

app/views/start_session/index.html.erb
<div class="row-fluid">
  <div class="jumbotron">
		<div class="page-header" id="welcome-index-h1">
			<h1>Grocery Cost Calculator</h1>
		</div>
	</div>
</div>

app/views/start_session/signin.html.erb
<div class="row">
	<div class="col-md-3"></div>
	<div class="col-md-6">
			<h1>Sign in</h1>
	  	<%= form_for @user, url: do_signin_path, method: "post" do |f| %>
			  <div class="form-group">
		  	  <%= render "shared/validation_messages", :target => @user %>
					<%= f.label :email, class: "control-label" %>
					<%= f.text_field :email, :placeholder => "email@domain.com", class: "form-control" %>
			  </div>
			  <div class="form-group">
					<%= f.label :password, class: "control-label" %>
					<%= f.password_field :password, :placeholder => "Enter a password", class: "form-control" %>
			  </div>
			  <%= f.submit "Log in", class: "btn btn-primary" %>
			  <%= link_to "Sign up", signup_path %>
			<% end %>
		</div>
	<div class="col-md-3"></div>
</div>

app/views/start_session/signup.html.erb
<div class="container-fluid">
	<div class="row">
		<div class="col-md-3"></div>
		<div class="col-md-6">
			<h2>Sign up</h2>
				<%= form_for @user, url: do_signup_path do |f| %>
				  <%= render "shared/validation_messages", :target => @user %>
				<div class="form-group">
					<%= f.label :email, class: "control-label" %>
					<%= f.text_field :email, :placeholder => "email@domain.com", class: "form-control" %>
					<%= f.label :email_confirmation, class: "control-label" %>
					<%= f.text_field :email_confirmation, class: "form-control" %>
				</div>
				<div class="form-group">
					<%= f.label :password, class: "control-label" %>
					<%= f.password_field :password, :placeholder => "Enter a password", class: "form-control" %>
					<%= f.label :password_confirmation, class: "control-label" %>
					<%= f.password_field :password_confirmation, class: "form-control" %>
				</div>
				<div class="form-group">
					<%= f.submit "Sign up", class: "btn btn-primary" %>
					<%= link_to "Sign in", signin_path %>
				</div>
				<% end %>
			</div>
		<div class="col-md-3"></div>
	</div>
</div>