config/routes.rb
Rails.application.routes.draw do

  root 'start_session#index'
  
  get '/signin' => 'start_session#signin'
  get '/signup' => 'start_session#signup'
  post '/do_signup' => 'start_session#do_signup'
  post '/do_signin' => 'start_session#do_signin'
  get '/logout' => 'session#logout'

  get '/profile' => 'session#profile'
  get '/settings' => 'session#settings'

  namespace :admin do
    resources :users
    resources :grocery_lists
    resources :store_products
    resources :products
    resources :stores
  end

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
	<head>
	  <title>GroceryCost</title>
	  <meta name="viewport" content="width=device-width, initial-scale=1">
	  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
	  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
	  <%= csrf_meta_tags %>
	</head>
	<body>
		<nav class="navbar">
			<div class="container-fluid">
		    <div class="navbar-header">
		    	<% if session[:user_id] == nil %>
		        <%= link_to "HOME!!!", root_path, :class => "navbar-brand" %>
		      <% else %>
		        <%= link_to "HOME!!!", profile_path, :class => "navbar-brand" %>
		      <% end %>
		    </div>
		    <div class="nav navbar-nav navbar-right">
			    <ul class="nav navbar-nav">
			    	<% if session[:user_id] == nil %>
			    		<li><%= link_to "Sign up", signup_path %></li>
			     	  <li><%= link_to "Sign in", signin_path %></li>
			    	<% else %>
			    	  <li>Welcome, <%= current_user.email %>!</li>
			    	  <li><%= link_to " • ", settings_path %></li>
				    	<li><%= link_to "Log out", logout_path %></li>
		     	  <% end %>
	  	  	</ul>
	  		</div>
	  	</div>
		</nav>
		<% if current_user && current_user.is_admin %>
		  <nav class="navbar">
			  <div class="container-fluid">
			  	<ul class="nav navbar-nav">
				  	<li><%= link_to "Users", admin_users_path %></li>
				  	<li><%= link_to "Grocery Lists", admin_grocery_lists_path %></li>
				  	<li><%= link_to "Store Products", admin_store_products_path %></li>
				  	<li><%= link_to "Products", admin_products_path %></li>
				  	<li><%= link_to "Stores", admin_stores_path %></li>
				  	<li>+</li>				  	
				  </ul>
			  </div>
		  </nav>
		<% end %>
	  <div class="container-fluid">
			<%= yield %>
	  </div>
	</body>
</html>